### ISSUE TITLE
Can blastFoam be used on CentOS？

### ISSUE THREAD

**Issue by zhaokangchun** [synthetik-technologies/blastfoam#39]
Dear Jeff,
When I tried to install blastFoam on a supercomputer, I ran into some troubles. It shows that there is a problem with the code. The supercomputer uses a CentOS system. I want to ask you, can blastFoam be used on CentOS? Or is there a problem with my installation steps?
BlastFoam works well on ubuntu. It is very helpful for my research. Thank you very much for your work and blastFoam. 

![ec5abd922fa1912122d40fbd477286f](https://user-images.githubusercontent.com/83912913/117575237-8c396a00-b113-11eb-8d95-dec890748fdd.png)

**Comment by jheylmun** [comment]
Hello, 
As long as OpenFOAM can be installed, blastFoam should not have any issues. The problem that you are seeing is just a difference between the most current version of OpenFOAM-7 and the precompiled version. I (hopefully) just pushed a fix that should resolve this problem. Please let me know if you are still having issues though since my fix may have been specific to ubuntu.

Thanks,
Jeff
