### ISSUE TITLE
limitTemperature (fvConstraints) not working

### ISSUE THREAD

**Issue by DanielM1123** [synthetik-technologies/blastfoam#51]
Dear blastFOAM team,

on the basis of the shockTube tutorial case, I did calculation with the blastFoam solver for a self written equation of state. To compare the results, I also had a run with the same setup but with an ideal gas EOS. Both cases utilize a limitTemperature constraint (for my further work), but running blastFoam results directly in a segmentation fault (see file attached). 

Thank you in advance for your efford.

Best regards,
Daniel

[log_blastFoam.txt](https://github.com/synthetik-technologies/blastfoam/files/8481428/log_blastFoam.txt)

**Comment by jheylmun** [comment]
Hi Daniel,
Based on a quick test on my end, I am guessing that you just need to add 
libs ("libfvConstraints.so");
to the entry in the fvConstraints file.  If this line is not included the list of options is empty which is why you are getting those weird errors. In the user guide, the fvModels/fvConstraints section goes over some other libraries that can be included for additional features, all added the same way (or in a list, i.e. libs ("lib1.so" "lib2.so" ....)).

temp
{
    libs ("libfvConstraints.so");
    type limitTemperature;
    selectionMode all;
    min 0; 
    max 10;
}

Thanks,
Jeff

**Comment by DanielM1123** [comment]
Hi Jeff,

thank you very much for your answer. I implemented your suggestions and it's working now for me.

Best regards,
Daniel
