### ISSUE TITLE
Adaptive Mesh Problem

### ISSUE THREAD

**Issue by annaw101** [synthetik-technologies/blastfoam#58]
Attempting to model the results of the Zong et al. paper located in section 4.2.1 circular columns. The image below taken from the paper demonstrates the domain that is being modeled. For computational efficiency, the model represents a quarter of the domain. A 150 kg charge (total quarter weight) of TNT detonates and columns (ie blast fence) with a radius of 50 mm and 100 mm of spacing were placed 5m away from the TNT.  These columns were created as STL files found in triSurface. To determine the effectiveness of the blast fence, pressure probes were placed 3m behind the wall. 

The case runs to completion when the adaptive hex mesh (as labeled dynamicMeshDict) is turned off, but for some reason does not run at all when mesh is turned on. **Would appreciate any insight into why this feature is not working.** Files for case attached below named as annaBlastFence16.

Thank you!!

![image](https://user-images.githubusercontent.com/50217791/187101017-5a85bda5-b0d9-4dce-ab3d-d27f381f758a.png)
*PC: Zong et al's Development of a New Fence Type Blast Wall

[Zong et al. - 2017 - Development of a New Fence Type Blast Wall for Bla.pdf](https://github.com/synthetik-technologies/blastfoam/files/9440700/Zong.et.al.-.2017.-.Development.of.a.New.Fence.Type.Blast.Wall.for.Bla.pdf)

[annaBlastFence16.zip](https://github.com/synthetik-technologies/blastfoam/files/9440690/annaBlastFence16.zip)

**Comment by jheylmun** [comment]
Hello,
The problem with using AMR in this case is that the refinement method used in snappyHexMesh is incompatible with the refinement used by blastFoam in 2D. There are a couple of ways to get around this. First, you can use some sort of grading so that your unrefined mesh is fine enough to capture the geometry without any additional refinement. Secondly, you can use setRefinedFields utility to refine the fence, then use the subsetMesh utility to remove the fence (see [this](https://github.com/synthetik-technologies/blastfoam/blob/master/tutorials/blastFoam/internalDetonation/internalDetonation_withObstacleAndGlass/Allrun)tutorial) )

**Comment by RufinoN** [comment]
> Hello, The problem with using AMR in this case is that the refinement method used in snappyHexMesh is incompatible with the refinement used by blastFoam in 2D. There are a couple of ways to get around this. First, you can use some sort of grading so that your unrefined mesh is fine enough to capture the geometry without any additional refinement. Secondly, you can use setRefinedFields utility to refine the fence, then use the subsetMesh utility to remove the fence (see [this ](https://github.com/synthetik-technologies/blastfoam/blob/master/tutorials/blastFoam/internalDetonation/internalDetonation_withObstacleAndGlass/Allrun)tutorial)

does this apply to a 3D case as well?
I'm trying to run a 3D case using blastFSIFoam, but as soon as my detonation touch the walls of my 3d models (meshed with snappyHexMesh) the solver fails with floating points error. If no, what is the correct way to do this?

Best,
Newton R
