### ISSUE TITLE
Murnaghan EOS

### ISSUE THREAD

**Issue by f-horsch** [synthetik-technologies/blastfoam#64]
Hello Jeff,
I have a question about the Murnaghan Equation of State.
The JWL++ (Souers et al., 2000) is implemented in blastFoam. The unreacted state is described via the Murnaghan EOS, the reacted state via the JWL EOS in C-form.
A Grüneisen coefficient (Gamma) is required in blastFoam, but is not present in the Murnaghan EOS. Now to my question:
Why does blastFoam need this coefficient and how is it calculated?
For Example in the twoChargeDetonation tutorial, Gamma is set to 0.35 for RDX and TNT.

Furthermore, according to (Souers et al., 2000), the speed of sound is defined by 
c² = 1/(rho0 * kappa * v^(n-1))      with v = rho0/rho
but in blastFoam the speed of sound is calculated like this:
`Foam::scalar Foam::Murnaghan<Specie>::cSqr`
`return pow(rho/rho0_, n_ - 1.0)/(rho0_*n_*kappa_)`
In my opinion, the n in the denominator is not right or is it related to the Gamma?

Kind regards,
Florian

**Comment by jheylmun** [comment]
Hi Florian,
The Gruneisen coefficient is defined as (dp/de)*1/rho and is used when multiple equation of states are blended (Zheng et al., 2011, A solution adaptive
simulation of compressible multi-fluid flows with general equation of state.) Technically this should be 0 for the Murnaghan EOS since it is temperature independent, but for all the solid equation of states it is purely used as the blending coefficient. We typically use the explosive Gamma.

You are correct that the speed of sound is incorrect and a bug fix should be up today. Thanks for the catch.

Jeff
