### ISSUE TITLE
Simulating Underwater Bubble Formation Using blastFoam

### ISSUE THREAD

**Issue by jiaqiwang969** [synthetik-technologies/blastfoam#66]
Dear Author,

I have been using your code to simulate compressed air explosions and have been getting very good results. I am now interested in simulating underwater bubble formation, which I recently came across in this video: https://www.youtube.com/watch?v=FBapRUolruM&t=1s. As you may know, these bubbles are composed of vapor and gases dissolved in water and are formed around objects such as vibrating plates or hydrofoils with high lift-to-drag ratios, such as propellers or water wings. The surface pressure around these objects can drop dramatically, eventually falling below the saturated vapor pressure at the given temperature and causing small bubbles to form, which then grow as they absorb more gas.

I was wondering if it would be possible to attempt to simulate this phenomenon. I am aware that the density of water is much higher than that of air, so I am not sure if this would pose any difficulties in modeling this problem. Additionally, water is incompressible.

Would you be able to provide any insights into the feasibility and potential challenges of simulating this type of problem?

Sincerely,
Jiaqi

**Comment by jheylmun** [comment]
Hi Jiaqi,
Currently we do not have any mass transfer (aka liquid water to water vapor) in the standard blastFoam solver, and we have only done this kind of simulation via the equation of state. The linearTillotson EOS is a very simple way to do this, however you can also use the tabulated equation of state if you know the p-rho-e relation.

Ideally this would be done using the blastEulerFoam solver so that drag and lift can be accounted for without out resolving the interface, but multiple fluid phases are not currently supported due to the lack of pressure relaxation and mass transfer models between fluid phases. 

The standard multiphaseEulerFoam and compressibleInterFoam are probably the best approach currently, though the are not ideal due to the fact that they are generally for lower Mach numbers. Unfortunately there are no plans currently for adding this capability, but hopefully sometime in the future.

Thanks,
Jeff
