### ISSUE TITLE
How to visualize validation and tutorial results?

### ISSUE THREAD

**Issue by GlenFlint** [synthetik-technologies/blastfoam#7]
[log.blockMesh.log](https://github.com/synthetik-technologies/blastfoam/files/4886594/log.blockMesh.log)
[log.decomposePar.log](https://github.com/synthetik-technologies/blastfoam/files/4886595/log.decomposePar.log)
[log.setRefinedFields.log](https://github.com/synthetik-technologies/blastfoam/files/4886596/log.setRefinedFields.log)
[log.snappyHexMesh.log](https://github.com/synthetik-technologies/blastfoam/files/4886597/log.snappyHexMesh.log)
[log.surfaceFeatures.log](https://github.com/synthetik-technologies/blastfoam/files/4886598/log.surfaceFeatures.log)

Please add information about how to visualize the results of the validation and tutorials.  building3D runs in 10 seconds on my system. The logs show no errors.  But there appears to be no output.  Where can I look to determine if building3D (or any of the tutorials or validation) is working or not?

**Comment by ifmfr** [comment]
Please have a look at the script [Allrun](https://github.com/synthetik-technologies/blastfoam/blob/master/tutorials/blastFoam/building3D/Allrun), the final call of the solver `# runParallel $(getApplication)` is commented out. In order to visualize your model/output you can use OpenFoam's implementation of Paraview with `paraFoam -builtin`.

**Comment by jheylmun** [comment]
I removed the comment from the script so the case should run as expected now.
